### ISSUE TITLE
Inconsistencies for inputs to create models

### ISSUE THREAD

**Issue by camilogarciabotero** [BioJulia/SubstitutionModels.jl#31]
When creating models using the different methods I found an inconsistency on how they can be created out of their inputs:

## Expected Behavior

The `K80` can be easily created with a `Vector{Float64}` input:

```
K80([0.21568627450980393, 0.2647058823529412])
```

However the `F80` fails to this input type, instead needs comma-separated values:

```
F81([0.21568627450980393, 0.2647058823529412, 0.2549019607843137, 0.2647058823529412])
```

ERROR: MethodError: no method matching F81(::Vector{Float64})

Closest candidates are:
  F81(::A, ::A; safe) where A<:AbstractArray
   @ SubstitutionModels ~/.julia/packages/SubstitutionModels/GIGot/src/nucleic_acid/f81/outer_constructors.jl:12
  F81(::F, ::F, ::F, ::F; safe) where F<:Float64
   @ SubstitutionModels ~/.julia/packages/SubstitutionModels/GIGot/src/nucleic_acid/f81/outer_constructors.jl:1
  F81(::F, ::F, ::F, ::F, ::F; safe) where F<:Float64
   @ SubstitutionModels ~/.julia/packages/SubstitutionModels/GIGot/src/nucleic_acid/f81/outer_constructors.jl:6

Stacktrace:
 [1] top-level scope
   @ REPL[294]:1

## Current Behavior

The thing is that it could be created as:

```
F81(0.21568627450980393, 0.2647058823529412, 0.2549019607843137, 0.2647058823529412)
```
```
Felsenstein 1981 model (relative rate form)
π = [0.21568627450980393, 0.2647058823529412, 0.2549019607843137, 0.2647058823529412]
```

This also happens with the `convert` method.

**Comment by jangevaare** [comment]
Sorry, I missed this. 

This is because F81 requires a vector of base frequencies, which are not utilized in K80. These are represented separately from the other model parameters. Perhaps this could be better represented via the type hierarchy or something. Open to suggestions which could better support your use.

**Comment by jangevaare** [comment]
Closing this. Please reopen or contact directly if you'd like to discuss further @camilogarciabotero
